version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: DronesDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

